// models/profile.js
export default (sequelize, DataTypes) => {
  const Profile = sequelize.define(
    "Profile",
    {
      id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
        autoIncrement: true,
        allowNull: false,
      },
      user_id: {
        type: DataTypes.BIGINT,
        allowNull: false,
        references: {
          model: "users",
          key: "id",
        },
        onDelete: "CASCADE",
      },
      first_name: {
        type: DataTypes.STRING(100),
      },
      last_name: {
        type: DataTypes.STRING(100),
      },
      full_name: {
        type: DataTypes.STRING(201), // generated by DB, Sequelize just reads it
      },
      date_of_birth: {
        type: DataTypes.DATEONLY,
      },
      gender: {
        type: DataTypes.STRING(20),
        validate: {
          isIn: [["male", "female", "other", "prefer_not_to_say"]],
        },
      },
      avatar_url: {
        type: DataTypes.STRING(500),
      },
      bio: {
        type: DataTypes.TEXT,
      },
      preferences: {
        type: DataTypes.JSON,
      },
    },
    {
      tableName: "profiles",
      timestamps: true,
      createdAt: "created_at",
      updatedAt: "updated_at",
    }
  );

  Profile.associate = (models) => {
    Profile.belongsTo(models.User, {
      foreignKey: "user_id",
      as: "user",
    });
  };

  return Profile;
};
